// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otocyunlsazwpxqwxlwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90b2N5dW5sc2F6d3B4cXd4bHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjkwNzksImV4cCI6MjA2Mzk0NTA3OX0.ezk-Lcd7QKNDD6i4Z1wzkI3pUsOOt27IoWuBR6DYvj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);